const profileActionTypes = {
    PROFILE_ACTION_FAILURE: 'PROFILE_ACTION_FAILURE',
    FETCH_USER_EVENTS_START: 'FETCH_USER_EVENTS_START',
    FETCH_USER_EVENTS_SUCCESS: 'FETCH_USER_EVENTS_SUCCESS',
    FETCH_USER_POSITIONS_START: 'FETCH_USER_POSITIONS_START',
    FETCH_USER_POSITIONS_SUCCESS: 'FETCH_USER_POSITIONS_SUCCESS',
    FETCH_USER_NOMINEES_START: 'FETCH_USER_NOMINEES_START',
    FETCH_USER_NOMINEES_SUCCESS: 'FETCH_USER_NOMINEES_SUCCESS',
    ADD_USER_EVENT_START: 'ADD_USER_EVENT_START',
    ADD_USER_EVENT_SUCCESS: 'ADD_USER_EVENT_SUCCESS',
    ADD_USER_NOMINEE_START: 'ADD_USER_NOMINEE_START',
    ADD_USER_NOMINEE_SUCCESS: 'ADD_USER_NOMINEE_SUCCESS',
    ADD_USER_POSITION_START: 'ADD_USER_POSITION_START',
    ADD_USER_POSITION_SUCCESS: 'ADD_USER_POSITION_SUCCESS',
    CLEAR_PROFILE_DATA: 'CLEAR_PROFILE_DATA'
}

export default profileActionTypes;