export const eventActionTypes = ({
    FETCH_START: 'FETCH_START',
    FETCH_FAILURE: 'FETCH_FAILURE',
    SET_EVENTS_SUCCESS: 'SET_EVENTS_SUCCESS',
    SET_POSITIONS_SUCCESS: 'SET_POSITIONS_SUCCESS',
    SET_NOMINEES_SUCCESS: 'SET_NOMINEES_SUCCESS',
})
export default eventActionTypes;