export const eventActionTypes = ({
    FETCH_START: 'FETCH_START',
    FETCH_FAILURE: 'FETCH_FAILURE',
    SET_EVENTS_SUCCESS: 'SET_EVENTS_SUCCESS',
    SET_POSITIONS_SUCCESS: 'SET_POSITIONS_SUCCESS',
    SET_NOMINEES_SUCCESS: 'SET_NOMINEES_SUCCESS',
    VOTE_NOMINEE_START: 'VOTE_NOMINEE_START',
    VOTE_NOMINEE_SUCCESS: 'VOTE_NOMINEE_SUCCESS',
    VOTE_NOMINEE_FAILURE: 'VOTE_NOMINEE_FAILURE'
})
export default eventActionTypes;