const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_EVENTS: 'SET_USER_EVENTS',
    SET_USER_POSITIONS: 'SET_USER_POSITIONS',
    SHOW_SIGNIN_SIGNOUT: "SHOW_SIGNIN_SIGNOUT",
    FORM_SWITCH: "FORM_SWITCH"
}

export default UserActionTypes;