const UserActionTypes = {
    USER_ACTION_START: 'USER_ACTION_START',
    USER_ACTION_OTHERS_START: 'USER_ACTION_OTHERS_START',
    USER_ACTION_FAILURE: 'USER_ACTION_FAILURE',
    SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
    SET_USER_EVENTS_SUCCESS: 'SET_USER_EVENTS_SUCCESS',
    SET_USER_POSITIONS_SUCCESS: 'SET_USER_POSITIONS_SUCCESS',
    SET_USER_NOMINEES_SUCCESS: 'SET_USER_NOMINEES_SUCCESS',
    USER_SIGNIN_START: 'USER_SIGNIN_START',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNUP_START: 'USER_SIGNUP_START',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNOUT_START: 'USER_SIGNOUT_START',
    USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS'
}

export default UserActionTypes;