const UserActionTypes = {
    USER_ACTION_START: 'USER_ACTION_START',
    USER_ACTION_FAILURE: 'USER_ACTION_FAILURE',
    SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
    SET_USER_EVENTS_SUCCESS: 'SET_USER_EVENTS_SUCCESS',
    SET_USER_POSITIONS_SUCCESS: 'SET_USER_POSITIONS_SUCCESS',
    SET_USER_NOMINEES_SUCCESS: 'SET_USER_NOMINEES_SUCCESS'
}

export default UserActionTypes;